### ISSUE TITLE
eHD driver for old kernels

### ISSUE THREAD

**Issue by ua0lnj** [pbiering/ReelBoxNG#9]
This commit [https://github.com/pbiering/ReelBoxNG/commit/dc248a422fe4e2ce99f89a3534c3d3f29aa6252a](url) was lost.

Also in Makefile need:
$(MAKE) V=1 -C $(KERNELPATH) M=$(shell pwd) modules
instead
$(MAKE) V=1 -C $(KERNELPATH) SUBDIRS=$(shell pwd) modules

It is not clear why the SUBDIRS is used, this is need for kernel < 2.6.6.

**Comment by pbiering** [comment]
That is strange...no clue why it got lost...readded now: https://github.com/pbiering/ReelBoxNG/commit/2a88f08311cc518e1e231322b3c772d17fe41d8d

Please check and if working, close the issue, thank you!

**Comment by ua0lnj** [comment]
No hexint error now.
But the second error remained.

make[1]: Entering directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/driver'
echo /lib/modules/5.4.0-65-generic/build
/lib/modules/5.4.0-65-generic/build
make V=1 -C /lib/modules/5.4.0-65-generic/build SUBDIRS=/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/driver modules
make[2]: Entering directory '/usr/src/linux-headers-5.4.0-65-generic'
make -f ./scripts/Makefile.build obj=arch/x86/entry/syscalls all
make -f ./scripts/Makefile.build obj=scripts/basic
rm -f .tmp_quiet_recordmcount
make -f ./scripts/Makefile.build obj=arch/x86/tools relocs
make[3]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
arch/x86/Makefile:232: recipe for target 'archscripts' failed
make[2]: *** [archscripts] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.4.0-65-generic'
Makefile:37: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/driver'
Makefile:47: recipe for target 'x86' failed
make: *** [x86] Error 1

In Makefile need:
$(MAKE) V=1 -C $(KERNELPATH) **M**=$(shell pwd) modules
instead
$(MAKE) V=1 -C $(KERNELPATH) **SUBDIRS**=$(shell pwd) modules

**Comment by pbiering** [comment]
sorry, forgotten, can you try https://github.com/pbiering/ReelBoxNG/commit/961e0ab649225ae59761d909f86967aba32a2959
Looks like akmods is not really using the Makefile - the install section has also still some leftover code...

**Comment by ua0lnj** [comment]
It's compiled if I swap:

ifneq ($(findstring 2.6,$(KERNELRELEASE)),)
 export-objs:=
 list-multi:=
 KMODSUF:= ko
 KMAKEOPTION = **SUBDIRS**
else
 KMODSUF:= o
 KMAKEOPTION = **M**
endif

**Comment by pbiering** [comment]
did a "major" rewrite as "findstring" is not reliable (would e.g. catch also 5.2.6): https://github.com/pbiering/ReelBoxNG/commit/5a25663de5dfb73b61c75bf3bc87e867cb842323

please test again, you can also run following for testing the vars

`make var-test`

**Comment by ua0lnj** [comment]
The driver is not going at all:
 
root@ua0lnjvdr:/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3# make x86
for i in x86/driver x86/hdboot x86/hdctrld x86/hdfbctl x86/shmnetd ; do \
        make -C $i || exit 1;\
done
make[1]: Entering directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/driver'
KERNEL_VERSION     =328704
KERNEL_VERSION_TEST=132614
KERNEL_FLAG_TEST   =1
KMAKEOPTION        =M
KMODSUF            =ko
KERNELPATH         =/lib/modules/5.4.0-65-generic/build
MODULEPATH         =/lib/modules/5.4.0-65-generic/extra
make[1]: Leaving directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/driver'
make[1]: Entering directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/hdboot'
gcc -MM -MG  -D__LINUX__ -I../../src/include -I../../src/driver *.c > .dependencies
gcc -D__LINUX__ -I../../src/include -I../../src/driver -O2 -Wall -c hdboot.c
gcc   hdboot.o   -o hdboot
strip hdboot
make[1]: Leaving directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/hdboot'
make[1]: Entering directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/hdctrld'
gcc -MM -MG  -D__LINUX__ -I../../src/include *.c > .dependencies
gcc -D__LINUX__ -I../../src/include -O3 -Wall -c hdctrld.c
gcc -D__LINUX__ -I../../src/include -O3 -Wall -c hdvideo.c
gcc -D__LINUX__ -I../../src/include -O3 -Wall -c hdshmlib.c
gcc   hdctrld.o hdvideo.o hdshmlib.o  -lpthread -o hdctrld
strip hdctrld
make[1]: Leaving directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/hdctrld'
make[1]: Entering directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/hdfbctl'
gcc -MM -MG  -D__LINUX__ -I../../src/include *.c > .dependencies
gcc -D__LINUX__ -I../../src/include -O3 -Wall -c hdfbctl.c
gcc -D__LINUX__ -I../../src/include -O3 -Wall -c hdshmlib.c
gcc   hdfbctl.o hdshmlib.o  -lpthread -o hdfbctl
strip hdfbctl
make[1]: Leaving directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/hdfbctl'
make[1]: Entering directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/shmnetd'
gcc -MM -MG  -D__LINUX__ -I../../src/include -I../../src/driver *.c > .dependencies
gcc -D__LINUX__ -I../../src/include -I../../src/driver -g  -O2 -Wall -c shmnetd.c
shmnetd.c: In function ‘main’:
shmnetd.c:106:10: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
          system("/sbin/ifconfig tun0 " MASTER_IP " netmask " NETMASK " mtu 8300;"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 "route add default gw " HOST_IP );
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shmnetd.c:109:10: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
          system("/sbin/ifconfig tun0 " HOST_IP " netmask " NETMASK " mtu 8300");
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
shmnetd.c:134:25: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
                         write(tunfd, txbuffer, ll);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -D__LINUX__ -I../../src/include -I../../src/driver -g  -O2 -Wall -c hdshmlib.c
gcc -D__LINUX__ -I../../src/include -I../../src/driver -g  -O2 -Wall -c hdchannel.c
gcc -g  shmnetd.o hdshmlib.o hdchannel.o   -o shmnetd
make[1]: Leaving directory '/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3/x86/shmnetd'
root@ua0lnjvdr:/usr/src/ReelBoxNG/src-reelvdr/utils/hdshm3#

**Comment by pbiering** [comment]
please test latest master or at least this commit: https://github.com/pbiering/ReelBoxNG/commit/05b3d86a088271a58d45a76bb707602b45e87d94

**Comment by ua0lnj** [comment]
All the same, no driver compilation.

**Comment by pbiering** [comment]
can you please report which of the X86_TARGETS are still not compiling on your system - enter each of them and call "make" inside.

**Comment by ua0lnj** [comment]
driver not compiled
hdboot compiled
hdctrld compiled
hdfbctl compiled
hdtsplay compiled
shmnetd compiled

**Comment by pbiering** [comment]
driver: fixed order in Makefile, now it's executing the compilation job - please try on your side

**Comment by ua0lnj** [comment]
Now all fine.
